import mongoose from 'mongoose';
const surveySchema = new mongoose.Schema({
  name: String,
  age: String,
  gender: String,
  occupation: String,
  fashionInterest: String,
  wardrobeSize: String,
  howDoYouPickOutfits: String,
  doYouLikeTryingNewStyles: String,
  howOftenDoYouBuyClothes: String,
  useFashionApps: [String], 
  rateFashionConfidence: String,
  digitalWardrobeInterest: String,
  doYouPlanOutfitsAhead: String,
  howDoYouFeelAboutCurrentStyle: String,
  styleInspirationSources: [String], 
  wouldYouUseMoodSuggestions: String,
  interestInChatStylist: String,
  wouldYouUseCustomization: String,
  areYouInterestedInStyleUpdates: String,
  budgetForStylingTools: String,
  preferredSubscriptionTier: String,
  willingnessToPay: String,
  mostValuedFeatures: [String], 
  biggestWardrobeChallenge: String,
  challengesWithMatchingItems: String,
  interestInEventBasedStyling: String,
  interestInWeatherBasedSuggestions: String,
  comfortWithAIStyling: String,
  opennessToSharePhotos: String,
  whatWouldMakeYouTrustThisApp: String,
  suggestions: String,
  improvementIdeas: String,
  futureWish: String,
},  { timestamps: true });
export default mongoose.model('Survey', surveySchema);